linters-settings:
  goimports:
    local-prefixes: github.com/NonokaM/WebDesignHub-API

linters:
  enable:
    - gofmt
    - goimports
    - gocritic
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - whitespace

run:
  timeout: 20m